version: '3.7'

services:
  visualizer-ui:
    image: ${VISUALIZER_UI_IMAGE_URI}
    ports:
      - "80:8080" # Map host's port 80 to the UI's port 8080
    networks:
      - app-network
    depends_on:
      - network-api

  network-api:
    image: ${NETWORK_API_IMAGE_URI}
    networks:
      - app-network
    depends_on:
      - network-db

  network-db:
    image: redis:6-alpine
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local